const ResourceConfig = {
  images: {
    characterLimbs: {
      body: [
        './src/assets/character_limbs/body/body_adventurer.svg',
        './src/assets/character_limbs/body/body_female.svg',
        './src/assets/character_limbs/body/body_player.svg',
        './src/assets/character_limbs/body/body_soldier.svg',
        './src/assets/character_limbs/body/body_zombie.svg',
      ],
      head: [
        './src/assets/character_limbs/head/head_adventurer.svg',
        './src/assets/character_limbs/head/head_female.svg',
        './src/assets/character_limbs/head/head_player.svg',
        './src/assets/character_limbs/head/head_soldier.svg',
        './src/assets/character_limbs/head/head_zombie.svg'],
      leftHand: [
        './src/assets/character_limbs/left_hand/left_hand_adventurer.svg',
        './src/assets/character_limbs/left_hand/left_hand_female.svg',
        './src/assets/character_limbs/left_hand/left_hand_player.svg',
        './src/assets/character_limbs/left_hand/left_hand_soldier.svg',
        './src/assets/character_limbs/left_hand/left_hand_zombie.svg'],
      leftLeg: [
        './src/assets/character_limbs/left_leg/left_leg_adventurer.svg',
        './src/assets/character_limbs/left_leg/left_leg_female.svg',
        './src/assets/character_limbs/left_leg/left_leg_player.svg',
        './src/assets/character_limbs/left_leg/left_leg_soldier.svg',
        './src/assets/character_limbs/left_leg/left_leg_zombie.svg'],
      rightHand: [
        './src/assets/character_limbs/right_hand/right_hand_adventurer.svg',
        './src/assets/character_limbs/right_hand/right_hand_female.svg',
        './src/assets/character_limbs/right_hand/right_hand_player.svg',
        './src/assets/character_limbs/right_hand/right_hand_soldier.svg',
        './src/assets/character_limbs/right_hand/right_hand_zombie.svg'],
      rightLeg: [
        './src/assets/character_limbs/right_leg/right_leg_adventurer.svg',
        './src/assets/character_limbs/right_leg/right_leg_female.svg',
        './src/assets/character_limbs/right_leg/right_leg_player.svg',
        './src/assets/character_limbs/right_leg/right_leg_soldier.svg',
        './src/assets/character_limbs/right_leg/right_leg_zombie.svg'],
    },
    themes: {
      choco: ['./src/assets/background/platform_choco.png'],
      dirt: ['./src/assets/background/platform_dirt.png'],
      grass: ['./src/assets/background/platform_grass.png'],
      metall: ['./src/assets/background/platform_metall.png'],
      purple: ['./src/assets/background/platform_purple.png'],
      sand: ['./src/assets/background/platform_sand.png'],
      snow: ['./src/assets/background/platform_snow.png'],
      tundra: ['./src/assets/background/platform_tundra.png'],
      cake: ['./src/assets/background/platform_cake.png'],
      choco_night: ['./src/assets/background/platform_choco.png'],
      dirt_night: ['./src/assets/background/platform_dirt.png'],
      grass_night: ['./src/assets/background/platform_grass.png'],
      metall_night: ['./src/assets/background/platform_metall.png'],
      purple_night: ['./src/assets/background/platform_purple.png'],
      sand_night: ['./src/assets/background/platform_sand.png'],
      snow_night: ['./src/assets/background/platform_snow.png'],
      tundra_night: ['./src/assets/background/platform_tundra.png'],
      cake_night: ['./src/assets/background/platform_cake.png'],
    },
    envElements: {
      castleDesert: [
        './src/assets/background/piramid.png',
        './src/assets/background/temple.png'],
      castle: [
        './src/assets/background/fence.png',
        './src/assets/background/house_beige_front.png',
        './src/assets/background/house_beige_side.png',
        './src/assets/background/house_grey_front.png',
        './src/assets/background/house_grey_side.png',
        './src/assets/background/tower_beige.png',
        './src/assets/background/tower_grey.png'],
      treeSnow: [
        './src/assets/background/tree04.png',
        './src/assets/background/tree06.png',
        './src/assets/background/tree12.png',
        './src/assets/background/tree15.png',
        './src/assets/background/tree22.png',
        './src/assets/background/tree33.png',
        './src/assets/background/tree35.png'],
      treeDesert: [
        './src/assets/background/tree16.png',
        './src/assets/background/tree17.png',
        './src/assets/background/tree18.png',
        './src/assets/background/tree19.png'],
      tree: [
        './src/assets/background/tree01.png',
        './src/assets/background/tree02.png',
        './src/assets/background/tree03.png',
        './src/assets/background/tree05.png',
        './src/assets/background/tree07.png',
        './src/assets/background/tree08.png',
        './src/assets/background/tree09.png',
        './src/assets/background/tree10.png',
        './src/assets/background/tree11.png',
        './src/assets/background/tree13.png',
        './src/assets/background/tree14.png',
        './src/assets/background/tree20.png',
        './src/assets/background/tree21.png',
        './src/assets/background/tree23.png',
        './src/assets/background/tree24.png',
        './src/assets/background/tree25.png',
        './src/assets/background/tree26.png',
        './src/assets/background/tree27.png',
        './src/assets/background/tree28.png',
        './src/assets/background/tree29.png',
        './src/assets/background/tree30.png',
        './src/assets/background/tree31.png',
        './src/assets/background/tree32.png',
        './src/assets/background/tree34.png'],
      clouds: [
        './src/assets/background/cloud1.png',
        './src/assets/background/cloud2.png',
        './src/assets/background/cloud3.png',
        './src/assets/background/cloud4.png',
        './src/assets/background/cloud5.png',
        './src/assets/background/cloud6.png',
        './src/assets/background/cloud7.png',
        './src/assets/background/cloud8.png',
        './src/assets/background/cloud9.png'],
      sun: [
        './src/assets/background/sun.png'],
      moon: [
        './src/assets/background/moon_full.png',
        './src/assets/background/moon_half.png'],
      sky: ['./src/assets/background/sky.svg'],
      night_sky: ['./src/assets/background/night_sky.svg'],
    },
  },
  sounds: {
    hitAttack: './src/assets/sounds/hit30.mp3.ogg',
    kickAttack: './src/assets/sounds/hit19.mp3.ogg',
    step: './src/assets/sounds/footstep04.ogg',
    shamandance: './src/assets/sounds/random_silly_chip_song.ogg',
    bgmusic: './src/assets/sounds/00 intro_0.ogg',
  },
};

export default ResourceConfig;
